#!/bin/bash

. /etc/neurodebian/cmdsettings.sh

    # Original serial version, we might want to switch between the two
    # upon -j
    for d in $alldists; do
      dfamily=${d%%-*}
      drelease=${d##*-}
    
      nd_updatedist $dfamily $drelease
    done
